import { PrismaClient } from "@prisma/client";//prsmaclient is autogenerate(the proccess of shcema.prisma to client is autogenerated client) which give you user/todos clients //sameAs import mongoose from mongoose

const prisma = new PrismaClient() //same as new mongoose

async function insertUser(email:string,password:string,firstName:string,lastName:string){
    const res = await prisma.user.create({
        data:{
            email,
            password,
            firstName,
            lastName
        },
        //why data field? if you wanto select only email from data u can say 
        select:{
            id:true,
            password:true
        }
    })
    console.log(res)
}

//insertUser("hello2@gmail.com","password","eswasdfar","landa")

interface UpdateParams{
    firstName:string,
    lastName:string
}

async function updateUser(email:string,{firstName,lastName}:UpdateParams){
     const res = await prisma.user.update({
        where:{email:email},
        data:{
            firstName,
            lastName
        }
    })
    console.log(res)
}

updateUser("hello2@gmail.com",{firstName:"jubli",lastName:"hills"})